# Generated by Django 6.0.5 on 2026-05-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('work', 'Работа'), ('personal', 'Личное'), ('study', 'Учёба'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
