# Generated by Django 6.0.5 on 2026-05-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('linux', '🐧 Linux'), ('python', '🐍 Python'), ('django', '🌐 Django'), ('docker', '🐳 Docker'), ('database', '🗄️ Базы данных'), ('network', '🌍 Сети / SSH'), ('git', '📦 Git'), ('other', '📚 Другое')], default='other', max_length=20),
        ),
    ]
