# Generated by Django 6.0.5 on 2026-05-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tech_category',
            field=models.CharField(blank=True, choices=[('linux', '🐧 Linux'), ('python', '🐍 Python'), ('django', '🌐 Django'), ('docker', '🐳 Docker'), ('database', '🗄️ Базы данных'), ('network', '🌍 Сети / SSH'), ('git', '📦 Git')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('work', 'Работа'), ('personal', 'Личное'), ('study', 'Учёба'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
